apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-ts
  namespace: app
  labels:
    example: "true"

spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 10%
  selector:
    matchLabels:
      api: app-ts
  template:
    metadata:
      labels:
        api: app-ts
        team: devops
    spec:
      securityContext:
        runAsUser: 1000
        #runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: node.kubernetes.io/instance-type
      #               operator: In
      #               values: [ "m5.large"]
      #             - key: node.kubernetes.io/capacity-type
      #               operator: In
      #               values: [ "on-demand"]
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchLabels:
        #           api: app-ts
        #       topologyKey: kubernetes.io/hostname
      # topologySpreadConstraints:
      #   - labalSelector:
      #       matchLabels:
      #         api: app-ts
      #     maxSkew: 1
      #     topologyKey: topology.kubernetes.io/zone
      #     whenUnsatisfiable: DoNotSchedule
      #serviceAccountName: sa-default
      containers:
        - name: app-ts
          image: danielrodriguess/app-ts:f10cf00
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          envFrom:
            - configMapRef:
                name: app-ts
            - secretRef:
                name: app-ts-secrets
          # env:
          #   - name: APP
          #     valuefrom:
          #       configmapkeyref:
          #         name: app-ts
          #         key: app-name
          #   - name: API_KEY
          #     valuefrom:
          #       secretkeyref:
          #         name: app-ts-secrets
          #         key: api-key
          ports:
            - containerPort: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 15
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 2
            successThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          # volumeMounts:
          #   - name: app-ts-data
          #     mountPath: /usr/src/app/uploads
      # volumes:
      #   - name: app-ts-data
      #     persistentVolumeClaim:
      #       claimName: first-pvc