apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $val := .Values.appConfigEnv }}
  {{ $key }}: "{{ $val }}"
  {{- end }}