apiVersion: v1
kind: Service

metadata:
  name: argocd-service
  namespace: app

spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: argocd-ingress
  namespace: app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.eusoudaniel.xyz
    cert-manager.io/cluster-issuer: cert-issuer-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  ingressClassName: nginx
  rules:
  - host: argocd.eusoudaniel.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-service
            port:
              number: 80
  tls:
  - hosts:
    - argocd.eusoudaniel.xyz
    secretName: argocd-ts-tls-secret
