apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: app-ts-ingress
  namespace: app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app.eusoudaniel.xyz
    cert-manager.io/cluster-issuer: cert-issuer-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  ingressClassName: nginx
  rules:
  - host: app.eusoudaniel.xyz
    http:
      paths:
      - path: /example-k8s
        pathType: Exact
        backend:
          service:
            name: app-ts-svc
            port:
              number: 80
  tls:
  - hosts:
    - app.eusoudaniel.xyz
    secretName: app-ts-tls-secret
